# Generated by Django 5.2.7 on 2025-10-30 16:29

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('periodo_pago', models.PositiveIntegerField(default=0, help_text='Valor entero positivo (incluye 0) que define el período de pago en días.', verbose_name='Período de Pago (días)')),
                ('periodo_revision', models.PositiveIntegerField(default=0, help_text='Valor entero positivo (incluye 0) que define el período de revisión en días.', verbose_name='Período de Revisión (días)')),
                ('ptdp', models.FileField(blank=True, help_text='Archivo PDF máximo de 5 MB.', null=True, upload_to='configuracion/ptdp/', validators=[core.models.validar_pdf, core.models.validar_tamano_pdf], verbose_name='PTDP (Documento PDF)')),
                ('actualizado_por', models.ForeignKey(blank=True, default=None, help_text='Último usuario que modificó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, default=None, help_text='Usuario que creó el registro originalmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
