# Generated by Django 5.2.7 on 2025-10-30 16:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='ptdp',
            field=models.FileField(blank=True, help_text='Archivo PDF máximo de 5 MB.', null=True, upload_to=core.models.ptdp_upload_path, validators=[core.models.validar_pdf, core.models.validar_tamano_pdf], verbose_name='PTDP (Documento PDF)'),
        ),
    ]
