# Generated by Django 5.2.7 on 2025-10-31 20:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_configuracion_ptdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='logo',
            field=models.ImageField(blank=True, help_text="Archivo PNG cuadrado de máximo 5 MB. Se almacenará como 'logo.png'.", null=True, upload_to=core.models.logo_upload_path, validators=[core.models.validar_logo_png, core.models.validar_tamano_imagen], verbose_name='Logo Institucional'),
        ),
    ]
