# Generated by Django 5.2.7 on 2025-11-04 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracion_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre corto y descriptivo del servicio (máx. 25 caracteres).', max_length=25, unique=True, verbose_name='Nombre del servicio')),
                ('actualizado_por', models.ForeignKey(blank=True, default=None, help_text='Último usuario que modificó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, default=None, help_text='Usuario que creó el registro originalmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
