# Generated by Django 5.2.7 on 2025-11-04 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre del estado (por ejemplo: Pendiente, En proceso, Respondido).', max_length=30, unique=True, verbose_name='Nombre del estado')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del propósito o uso de este estado.', verbose_name='Descripción')),
                ('color_hex', models.CharField(default='#6c757d', help_text='Color representativo en formato HEX (ejemplo: #28a745 para verde).', max_length=7, verbose_name='Color representativo (HEX)')),
                ('actualizado_por', models.ForeignKey(blank=True, default=None, help_text='Último usuario que modificó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, default=None, help_text='Usuario que creó el registro originalmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Contacto',
                'verbose_name_plural': 'Estados de Contacto',
                'ordering': ['nombre'],
            },
        ),
    ]
