# Generated by Django 5.2.7 on 2025-11-05 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estadocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se recibió la solicitud.')),
                ('nombres', models.CharField(help_text='Nombres del remitente (máx. 20 caracteres).', max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, help_text='Apellidos del remitente (opcional, máx. 20 caracteres).', max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Apellidos')),
                ('telefono', models.CharField(help_text='Número telefónico del remitente (incluya código país si aplica).', max_length=16, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message="El teléfono debe contener entre 7 y 15 dígitos y puede incluir '+' para código país.")], verbose_name='Teléfono')),
                ('correo', models.EmailField(help_text='Correo electrónico de contacto del remitente.', max_length=254, verbose_name='Correo electrónico')),
                ('descripcion', models.CharField(help_text='Detalle o descripción de la solicitud (máx. 200 caracteres).', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Descripción de la solicitud')),
                ('acepta_politica', models.BooleanField(default=False, help_text='El usuario debe aceptar la política de tratamiento de datos para enviar la solicitud.', verbose_name='Acepta política de tratamiento de datos')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del registro.')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la solicitud está activa o fue archivada/eliminada lógicamente.')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que realizó la última modificación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó')),
                ('estado', models.ForeignKey(blank=True, help_text="Estado actual de la solicitud. Si no se especifica, se intentará asignar 'PENDIENTE'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='core.estadocontacto', verbose_name='Estado de la solicitud')),
                ('servicio', models.ForeignKey(help_text='Servicio sobre el cual se solicita información.', on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='core.servicio', verbose_name='Servicio solicitado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['correo'], name='core_contac_correo_d6b0c3_idx'), models.Index(fields=['telefono'], name='core_contac_telefon_e6e6eb_idx'), models.Index(fields=['estado'], name='core_contac_estado__457596_idx')],
            },
        ),
    ]
