# Generated by Django 5.2.7 on 2025-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='email_administrativo',
            field=models.EmailField(default='karmindco@gmail.com', help_text='Correo electrónico institucional utilizado para notificaciones administrativas.', max_length=254, verbose_name='Correo Administrativo'),
        ),
    ]
