# Generated by Django 5.2.7 on 2025-11-06 21:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracion_email_administrativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='consentimiento_hash',
            field=models.CharField(blank=True, help_text='Hash único que acredita la integridad del consentimiento otorgado.', max_length=64, verbose_name='Huella digital del consentimiento (SHA256)'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha exacta en que el usuario aceptó la política de datos.', null=True, verbose_name='Fecha y hora de autorización'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='ip_autorizacion',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde la cual el usuario otorgó el consentimiento.', null=True, verbose_name='Dirección IP de autorización'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Información del navegador o dispositivo desde el cual se realizó el envío.', max_length=300, verbose_name='Agente de usuario (navegador/dispositivo)'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellidos',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='descripcion',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Descripción de la solicitud'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='core.estadocontacto', verbose_name='Estado de la solicitud'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombres',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='core.servicio'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Formato telefónico inválido.')], verbose_name='Teléfono'),
        ),
    ]
