# Generated by Django 5.2.7 on 2025-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contacto_consentimiento_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cliente_potencial',
            field=models.BooleanField(default=False, help_text='Indica si el contacto es un cliente potencial.'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del contacto o gestión realizada.', null=True),
        ),
    ]
