# Generated by Django 5.2.7 on 2025-11-07 22:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contacto_cliente_potencial_contacto_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPQRSF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(help_text='Nombre del tipo de solicitud (Ej: Petición, Queja, Reclamo, Sugerencia, Felicitación).', max_length=100, unique=True)),
                ('actualizado_por', models.ForeignKey(blank=True, default=None, help_text='Último usuario que modificó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, default=None, help_text='Usuario que creó el registro originalmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de PQRSF',
                'verbose_name_plural': 'Tipos de PQRSF',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PQRSF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombres', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', message='Formato telefónico inválido.')], verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('descripcion', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Descripción de la solicitud')),
                ('evidencia', models.FileField(blank=True, help_text='Archivo anexo opcional (máximo 5 MB).', null=True, upload_to='pqrsf_adjuntos/')),
                ('acepta_politica', models.BooleanField(default=False, help_text='El usuario debe aceptar la política de tratamiento de datos para enviar la solicitud.', verbose_name='Acepta política de tratamiento de datos')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del contacto o gestión realizada.', null=True)),
                ('ip_autorizacion', models.GenericIPAddressField(blank=True, help_text='IP desde la cual el usuario otorgó el consentimiento.', null=True, verbose_name='Dirección IP de autorización')),
                ('user_agent', models.CharField(blank=True, help_text='Información del navegador o dispositivo desde el cual se realizó el envío.', max_length=300, verbose_name='Agente de usuario (navegador/dispositivo)')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, help_text='Fecha exacta en que el usuario aceptó la política de datos.', null=True, verbose_name='Fecha y hora de autorización')),
                ('consentimiento_hash', models.CharField(blank=True, help_text='Hash único que acredita la integridad del consentimiento otorgado.', max_length=64, verbose_name='Huella digital del consentimiento (SHA256)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pqrs', to='core.estadocontacto', verbose_name='Estado de la PQRS')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tipo_PQRS', to='core.tipopqrsf')),
            ],
            options={
                'verbose_name': 'PQRSF',
                'verbose_name_plural': 'PQRSF',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['correo'], name='core_pqrsf_correo_85c165_idx'), models.Index(fields=['telefono'], name='core_pqrsf_telefon_ae39ea_idx'), models.Index(fields=['estado'], name='core_pqrsf_estado__8a1cce_idx')],
            },
        ),
    ]
